### ISSUE TITLE
Access to ArcGIS Server and SQL Server connection

### ISSUE THREAD

**Issue by dspinosa** [Innovate-Inc/CRS#14]
- [x] Need remote desktop access to the server where ArcGIS for Server is installed
- [x] Need ArcGIS Server to be able to communicate with the SQL Server
- [x] Need to have ArcGIS Desktop installed on ArcGIS Server

**Comment by jlherring** [comment]
For access info, see TeamCredentials doc on Sharepoint https://innovateinc.sharepoint.com/fileshares/_layouts/15/WopiFrame.aspx?sourcedoc=%7B6F6E8DAB-03F7-4503-9F34-06972872AD86%7D&file=TeamCredentials.docx&action=default

Still waiting on the following:
- Have access to ArcGIS Server box, but still waiting on ArcServer credentials -- received ArcServer creds
- Need to add arcgis user to SQL Server (once ArcServer creds are identified) so SQL and Arc can communicate -- still in process
- Need to find location of current web adaptor (if one exists on another machine), otherwise install web adaptor -- done

**Comment by jlherring** [comment]
Question for Julia?? Possibly -- need to determine if CRS will delete our Innovate sql accounts. May need to set up a datawriter account in SQL Server for the pypyodbc python script to connect to the database w/ once we are done w/ the contract

**Comment by jlherring** [comment]
Able to connection to SQL database and publish services, but web adaptor is not bound to any domain, so still cannot view rest services from outside of localhost.

Contacted Janeen for a "dev" domain as opposed to prod domain: https://arcgis.crs.org/arcgis/rest/services

Prod machine also appears to be 10.31, while dev is 10.41 ???

**Comment by jlherring** [comment]
dev connections are all successful

Dev ArcServer machine in Rackspace: 72.3.148.47:9191
Dev SQL Server machine in Rackspace: 10.15.230.244\dev
Dev domain: [http://arcgisdev.crs.org/arcgis/rest/services]
