### ISSUE TITLE
Check Field Mapping in Salesforce Original and Geocoded Tables.

### ISSUE THREAD

**Issue by dspinosa** [Innovate-Inc/CRS#25]
This is our test record.  Only one point exists. Why are we getting a value of 5 in the aggregated data?  Some field mappings are off by one.

![image](https://cloud.githubusercontent.com/assets/5093530/19355137/21130610-911e-11e6-83ac-f80e6480e6eb.png)

**Comment by jlherring** [comment]
CRS was thinking there was only 1 diocese per congressional district - but I don't think that's actually true.

There is definitely 1 diocese office per diocese and that relationship holds --
BUT I did have to further select out Archdioceses in a couple more places. Just because the "Institution_Sub_Type__c" is "Diocese" this still includes Archdioceses (which we do not want and create overlap)

**Comment by jlherring** [comment]
Shifted export over by one field, corrected the issue.
Congressional district data also did not contain unique Id's per district - had to create ID field and summarize points according to the new unique ID
